### ISSUE TITLE
Make compatible with other physics changing mods(such as speed potions)

### ISSUE THREAD

**Issue by appgurueu** [minetest-mods/hbsprint#12]
Feature Request. 
Do it the following : 
1 : when someone starts sprinting, use : 
`local physics = <sprinter>:get_player_physics()`

Amplification : 
```
physics.speed=physics.speed*sprint_speed
physics.jump=physics.jump*sprint_jump
```
Addition : 
```
physics.speed=physics.speed+sprint_speed
physics.jump=physics.jump+sprint_jump
```

to determine existing physics

2 : when someone stops, just apply reversing op : 

Amplification : 
```
physics.speed=physics.speed/sprint_speed
physics.jump=physics.jump/sprint_jump
```
Addition : 
```
physics.speed=physics.speed-sprint_speed
physics.jump=physics.jump-sprint_jump
```

Nice mod !
:1st_place_medal:

**Comment by tacotexmex** [comment]
No need to reinvent the wheel, use player_monoids.

**Comment by raymoo** [comment]
Does not work if you want to set overrides to 0 by multiplication.
