### ISSUE TITLE
When used in combination with most recent (5.0.0+) `hunger_ng`: setting raw hunger value does not work anymore

### ISSUE THREAD

**Issue by ghost** [minetest-mods/hbsprint#13]
Just a quick heads-up: The mod was updated to work with 5.0.0 only. When using the tagged 0.4.17 version of the mod all is fine, but when updating to the most recent version setting the raw custom attribute does not work anymore.

https://github.com/minetest-mods/hbsprint/blob/7170277c38c3c76588547f8127a95dc184d98182/init.lua#L90

It might not crash but it won’t have any effect. [Consider switching to the API instead](https://4w.gitlab.io/hunger_ng/README.API.html#changing-hunger) when you update the mod for 5.0.0 compatibility :smiley:

**Comment by tacotexmex** [comment]
Fixed in 559eba6. Guess I release it in tandem with the official 5.0.0 release.
