### ISSUE TITLE
Doesn't load properly

### ISSUE THREAD

**Issue by moeenio** [minetest-mods/hbsprint#18]
Installed this mod in `~/.minetest/mods/hbsprint`.
Enabled it on a world, and when launching the world getting this :
![image](https://user-images.githubusercontent.com/37651007/67460450-4f924480-f63b-11e9-921f-00de1a255c01.png)
![image](https://user-images.githubusercontent.com/37651007/67460474-6042ba80-f63b-11e9-908b-ed1cd119c2bc.png)

Running on Raspberry pi 4, raspbian Buster 10, xfce desktop.

**Comment by moeenio** [comment]
@tacotexmex

**Comment by tacotexmex** [comment]
Solved in #17, I think.

**Comment by moeenio** [comment]
No, it still shows this message.

**Comment by tacotexmex** [comment]
Please post the new error log.

@sfan5 please look at this.

**Comment by sfan5** [comment]
The `get_meta` API for player was introducted in Minetest 5.0, which is used since commit 97d05dd8423224eaf737ffd954ea36812861abe5.

Upgrade to Minetest 5.0 or use an older version of hbsprint.

**Comment by moeenio** [comment]
> Please post the new error log.

It's the same if I'm not wrong.

**Comment by moeenio** [comment]
> The `get_meta` API for player was introducted in Minetest 5.0, which is used since commit [97d05dd](https://github.com/minetest-mods/hbsprint/commit/97d05dd8423224eaf737ffd954ea36812861abe5).

Well, guess I'll need to wait for it to arrive in the Raspbian repositories :)
