### ISSUE TITLE
Sprinting immediately stops

### ISSUE THREAD

**Issue by orbea** [minetest-mods/hbsprint#21]
minetest: `5.1.1`
hbsprint: https://github.com/minetest-mods/hbsprint/commit/25472427e59899efa0b39cfad884dda03bacc06c
player_monoids: https://github.com/minetest-mods/player_monoids/commit/ed11a7395bb62bcdce3e314597edc06f4bb8a86e
hunger_ng: https://gitlab.com/4w/hunger_ng/-/commit/12741b9f3a659b100beb809f14bd3b4b5dc3ecfe
hudbars: https://repo.or.cz/minetest_hudbars.git/commit/7993feac0787b6ee32e5c3eda8360b18f761fb39

When running `hbsprint` I press and hold the `use` key which causes the player to sprint for a brief moment, but then immediately returns to normal speed while the sprint hud bar will continue to drain.

I expect the sprint should be a sustained speed boost rather than momentary as long as the stamina and hunger bars are adequately filled, am I doing something wrong?

**Comment by orbea** [comment]
I figured out the issue, there is some incompatibility with pova. I'm going to close this, please feel free to reopen if you feel there is something to address.

https://notabug.org/tenplus1/pova
https://notabug.org/TenPlus1/pova/commit/35a604e09a05da19d07d44662524483ca5832fd2

**Comment by tacotexmex** [comment]
Ah yes, hbsprint will compete with POVA. With player_monoids enabled, player_monoids will compete with POVA. xD
