### ISSUE TITLE
Press Special key, No speed effect

### ISSUE THREAD

**Issue by IFRFSX** [minetest-mods/hbsprint#26]
open mod: hudbars hbhunger hbsprint
minetest version: 5.3.0

**Comment by IFRFSX** [comment]
@SmallJoker

**Comment by SmallJoker** [comment]
it's a pity



@tacotexmex

**Comment by auouymous** [comment]
Try `sprint_speed = 3`. The default 1.3 is either too low to detect an increase or the engine has a bug that causes 1.3 to not increase speed. 1.5 was also too low but I noticed a slight increase with 1.9.

**Comment by IFRFSX** [comment]
No effect (I tested it on 5.4.0-dev), the same as no installation.
bar is not displayed

**Comment by auouymous** [comment]
Do you have the fast priv? The stamina bar auto-hides when full, and the fast priv doesn't drain stamina. `hudbars_autohide_stamina = false` will force the bar to always show.

With `sprint_speed = 2.15` the following is how the mod behaves for me:

No fast priv: sprinting works fine.

With fast priv: [disabled] sprinting doesn't work, [enabled] sprinting works, faster than normal.

With fly enabled: same as above, except when fast is enabled I am always fast and sprinting doesn't make me any faster.

**Comment by auouymous** [comment]
#27 fixes the fast and fly issues.

**Comment by SmallJoker** [comment]
Fixed by #27
