### ISSUE TITLE
Use minetest.after, not minetest.register_globalstep

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/hbsprint#4]
Recently learned that the `minetest.after` function is [less CPU intensive](https://github.com/minetest-mods/item_drop/commit/e84433d41ccd4abec1795acbcebe2895bc5be380#commitcomment-24123744) than `minetest.register_globalstep`.

For optimization, the `minetest.after` approach should be implemented.

(Am I doing it right, @sofar?)

**Comment by SmallJoker** [comment]
Use `minetest.after` when it improves the readability of the code. Please see https://github.com/minetest-mods/item_drop/commit/e84433d41ccd4abec1795acbcebe2895bc5be380#commitcomment-29486594

**Comment by tacotexmex** [comment]
Well did it? 🙂  (…improve the readability of the code?) ¯\_(ツ)_/¯

**Comment by tacotexmex** [comment]
Closing as the issue is accomplished.
