### ISSUE TITLE
Undeclared global variable

### ISSUE THREAD

**Issue by ghost** [minetest-mods/hbsprint#7]
WARNING[Main]: Undeclared global variable "player" accessed at ...le-0.4/bin/../games/hamlets_quest/mods/hbsprint/init.lua:127

**Comment by Poikilos** [comment]
I can confirm this on minetestserver 0.5.0-dev
(using my WIP subgame <https://github.com/expertmm/EnlivenMinetest/blob/master/etc/game-install-ENLIVEN>)

**Comment by sofar** [comment]
https://github.com/minetest-mods/hbsprint/blob/7fd2beb60f5486b804297902e1067daee272135b/init.lua#L127

`player` is always `nil` at this place, not sure why it's even passed here as an argument, it's nonsensical.

**Comment by tacotexmex** [comment]
Agreed. Since register_hudbar definition have a var for the bar being hidden by default ` I should just supplement `default_start_hidden` with `autohide` instead of `false`. 

First mod written from the ground up, sorry. 😊

**Comment by tacotexmex** [comment]
All done.

**Comment by Poikilos** [comment]
good job

**Comment by sofar** [comment]
c51ac933ba87c084bfed6b37305ff3799fbe3619 for reference.
